# Generated by Django 5.0 on 2024-03-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('showcase_projects', '0002_alter_rejectioncomment_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timepermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
