# Generated by Django 5.0 on 2024-03-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0003_alter_timepermission_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timepermission',
            old_name='time_add',
            new_name='time_finish',
        ),
        migrations.RenameField(
            model_name='timepermission',
            old_name='time_delete',
            new_name='time_start',
        ),
        migrations.RemoveField(
            model_name='timepermission',
            name='completed_add',
        ),
        migrations.RemoveField(
            model_name='timepermission',
            name='completed_delete',
        ),
    ]
