# Generated by Django 5.0 on 2024-04-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('showcase_projects', '0005_directionidentity_spheres_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='directionIdentity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='spheres',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='types',
        ),
        migrations.AlterField(
            model_name='directionidentity',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='types',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('processing', 'В обработке'), ('rejected', 'Отклонен')], default='processing', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='registration.customer')),
                ('directionIdentity', models.ManyToManyField(to='showcase_projects.directionidentity')),
                ('spheres', models.ManyToManyField(to='showcase_projects.spheres')),
                ('types', models.ManyToManyField(to='showcase_projects.types')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase_projects.order'),
        ),
        migrations.AlterField(
            model_name='rejectioncomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_comment', to='showcase_projects.order'),
        ),
    ]
