# Generated by Django 5.0 on 2024-04-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0006_remove_project_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
