# Generated by Django 5.0 on 2024-04-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0007_remove_project_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RejectionComment',
        ),
    ]
